### ISSUE TITLE
Contribute to Orchard Core

### ISSUE THREAD

**Issue by Piedone** [neglectedvalue/OrchardCore.Media.Amazon.S3#7]
This looks like an interesting project that would be a good addition to the official source of Orchard Core. Did you consider contributing it?

**Comment by neglectedvalue** [comment]
@Piedone Sure, with pleasure, but as far as I know OrchardCore uses Azure infrastructure. But if you are from Orchard team, I can create a PR in OrchardCore repo :)

**Comment by Piedone** [comment]
Great then! Yes, I was referring to a PR in the OC repo. I'd be happy to review it.

**Comment by neglectedvalue** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/11738 Merged.
